EBR/Blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'

urlpatterns = [
    path('',views.base, name='base'),
    path('user_registration',views.user_registration, name='user_registration'),
    path('user_login',views.user_login, name='user_login'),

    path('home', views.home, name='home'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('blog_post',views.blog_post, name='blog_post'),

    path('delete/<int:blo>',views.delete, name='delete'),
    path('edit/<int:blo>',views.edit, name='edit'),

    path('like/<int:blo>', views.like_blog, name='like_blog'),
    
    path('liked_blogs', views.liked_blogs, name='liked_blogs'),
    path('my_blogs', views.my_blogs, name='my_blogs'),
    path('trending_blogs', views.trending_blogs, name='trending_blogs'),
    path('profile', views.profile, name='profile'),

    path('edit-profile', views.edit_profile, name='edit_profile'),
]

EBR/EBR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='welcome.html'), name='welcome'),
    path('my_skills/', TemplateView.as_view(template_name='my_skills.html'), name='my_skills'),
    path('ChatLink/', TemplateView.as_view(template_name='ChatLink.html'), name='ChatLink'),

    path('Blog/', include('Blog.urls')),
    path('Ecom/', include('Ecom.urls')),
    path('Z_Resume/', include('Z_Resume.urls')),
    path('Z_Calculator/', include('Z_Calculator.urls')),
    path('Z_Tribute/', include('Z_Tribute.urls')),
    path('Z_Motivation/', include('Z_Motivation.urls')),
    path('Z_Quran/', include('Z_Quran.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EBR/Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Blog(models.Model):
    name = models.CharField(max_length=75)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='liked_blogs', blank=True)

    def __str__(self):
        return self.name

class BlogImage(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='blog_images')

    def __str__(self):
        return f"Image for {self.blog.name}"

EBR/Blog/forms.py
from django import forms
from .models import Blog, BlogImage
from django.forms import inlineformset_factory
from django.contrib.auth.models import User


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter blog name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your blog content'}),
        }

BlogImageFormSet = inlineformset_factory(
    Blog,
    BlogImage,
    fields=('image',),
    extra=9,  # Number of empty image upload fields to show
    can_delete=False
)

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

EBR/Blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import Blog, BlogImage
from .forms import BlogForm, BlogImageFormSet 
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from .forms import ProfileForm



@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('Blog:profile')
    else:
        form = ProfileForm(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form})


@login_required
def profile(request):
    user = request.user
    return render(request, 'profile.html', {'user': user})


def trending_blogs(request):
    # Fetch blogs, annotate with like count, and sort by likes in descending order
    blogs = Blog.objects.annotate(like_count=Count('likes')).order_by('-like_count')
    return render(request, 'trending.html', {'blogs': blogs})


def like_blog(request, blo):
    blog = get_object_or_404(Blog, id=blo)
    if request.user.is_authenticated:
        if request.user in blog.likes.all():
            blog.likes.remove(request.user)  # Unlike
        else:
            blog.likes.add(request.user)     # Like
    # Redirect back to the same page (or change as needed)
    return redirect(request.META.get('HTTP_REFERER', reverse('Blog:home')))


@login_required
def liked_blogs(request):
    # Get all Blog instances that the current user has liked.
    blogs = request.user.liked_blogs.all()  # Using the related_name defined in the Blog model
    return render(request, 'liked_blogs.html', {'blogs': blogs})


@login_required
def my_blogs(request):
    my_blog = Blog.objects.filter(author=request.user)
    return render(request, 'my_blogs.html', {'blogs': my_blog})

@login_required
def blog_post(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        formset = BlogImageFormSet(request.POST, request.FILES)

        if form.is_valid() and formset.is_valid():
            # Save the Blog instance but do not commit yet
            blog = form.save(commit=False)
            blog.author = request.user  # Set the blog's author
            blog.save()

            # Associate images with the blog
            formset.instance = blog
            formset.save()

            return redirect('Blog:home')
        else:
            return render(request, 'blog_post.html', {'form': form, 'formset': formset})
    else:
        form = BlogForm()
        formset = BlogImageFormSet()
    return render(request, 'blog_post.html', {'form': form, 'formset': formset})

#----------------------------------------------------------

def base(request):
    return render (request,'blog_base.html')

#----------------------------------------------------------

def user_registration(request):
    if request.method == 'POST':
        uname = request.POST['username']
        first = request.POST['fname']
        last = request.POST['lname']
        em = request.POST['email']
        password = request.POST['password']

        my_user = User.objects.create_user(username=uname, password=password, email=em)
        my_user.first_name= first
        my_user.last_name= last
        my_user.save()
        return redirect ('Blog:user_login')
    return render (request,'user_registration.html')

#----------------------------------------------------------

def user_login(request):
    if request.method == 'POST':
        uname = request.POST['username']
        password = request.POST['password']
        read = authenticate(username=uname, password=password)
        if read is not None:
            print(read)
            login(request, read)
            return redirect('Blog:home')
    return render(request, 'user_login.html')


def home(request):
    t = Blog.objects.all()
    return render (request,'home.html', {'blogs':t})


def user_logout(request):
    logout(request)
    return redirect('Blog:base')

#----------------------------------------------------------

@login_required
def delete(request,blo):
    p = Blog.objects.get(id=blo)
    p.delete()
    return redirect('Blog:home')

#----------------------------------------------------------

@login_required
def edit(request, blo):
    p = Blog.objects.get(id=blo)
    form = BlogForm(request.POST or None, request.FILES or None, instance=p)
    formset = BlogImageFormSet(request.POST or None, request.FILES or None, instance=p)
    
    if request.method == 'POST':
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('Blog:home')
    
    return render(request, 'edit.html', {'form': form, 'formset': formset})

EBR/Blog/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Wanderlust Home</title>

  <!-- Bootstrap & Fonts -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
  />
  <link
    href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Poppins:wght@300;400;600&display=swap"
    rel="stylesheet"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
  />

  <!-- Separated CSS -->
  <link rel="stylesheet" href="{% static 'Blog/css/home.css' %}">

</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Wander<span>lust</span></a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarContent"
        aria-controls="navbarContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <!-- Home Button -->
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}"
              href="{% url 'Blog:home' %}"
            >
              <i class="fas fa-home me-1"></i> Home
            </a>
          </li>
          <!-- Write Button -->
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a
              class="nav-link {% if request.resolver_match.url_name == 'blog_post' %}active{% endif %}"
              href="{% url 'Blog:blog_post' %}"
            >
              <i class="fas fa-edit me-1"></i> Write
            </a>
            {% else %}
            <a class="nav-link" href="{% url 'Blog:user_login' %}">
              <i class="fas fa-edit me-1"></i> Write
            </a>
            {% endif %}
          </li>
          <!-- Explore Button -->
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'explore' %}active{% endif %}"
              href="#"
            >
              <i class="fas fa-compass me-1"></i> Destinations
            </a>
          </li>
          <!-- Trending Button -->
          <li class="nav-item">
            <a
              class="nav-link {% if request.resolver_match.url_name == 'trending_blogs' %}active{% endif %}"
              href="{% url 'Blog:trending_blogs' %}"
            >
              <i class="fas fa-fire me-1"></i> Trending
            </a>
          </li>
        </ul>

        <div class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
          <div class="dropdown">
            <a
              class="nav-link user-dropdown dropdown-toggle"
              href="#"
              id="userDropdown"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <div class="user-avatar">{{ user.username|first|upper }}</div>
              <span class="d-none d-sm-inline">{{ user.username }}</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
              <li><a class="dropdown-item" href="{% url 'Blog:profile' %}"><i class="fas fa-user me-2"></i>Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'Blog:liked_blogs' %}"><i class="fas fa-heart me-2"></i>Liked Blogs</a></li>
              <li><a class="dropdown-item" href="{% url 'Blog:my_blogs' %}"><i class="fas fa-file-alt me-2"></i>My Blogs</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'Blog:base' %}"><i class="fas fa-home me-2"></i>Base Page</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item text-danger" href="{% url 'Blog:user_logout' %}"><i class="fas fa-sign-out-alt me-2"></i>Logout</a></li>
            </ul>
          </div>
          {% else %}
          <div class="d-flex">
            <a href="{% url 'Blog:user_login' %}" class="nav-link"><i class="fas fa-sign-in-alt me-1"></i> Login</a>
            <a href="{% url 'Blog:user_registration' %}" class="nav-link"><i class="fas fa-user-plus me-1"></i> Register</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

  {% block content %}
  <div class="container py-5">
    <div class="row">
      {% for blog in blogs %}
      <div class="col-lg-8 mx-auto mb-5">
        <div class="blog-card">
          {% if blog.images.all %}
          <div id="carousel-{{ blog.id }}" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              {% for image in blog.images.all %}
              <button
                type="button"
                data-bs-target="#carousel-{{ blog.id }}"
                data-bs-slide-to="{{ forloop.counter0 }}"
                class="{% if forloop.first %}active{% endif %}"
                aria-label="Slide {{ forloop.counter }}"
              ></button>
              {% endfor %}
            </div>
            <div class="carousel-inner">
              {% for image in blog.images.all %}
              <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <img src="{{ image.image.url }}" class="d-block w-100" alt="{{ blog.name }}" />
              </div>
              {% endfor %}
            </div>
            <button
              class="carousel-control-prev"
              type="button"
              data-bs-target="#carousel-{{ blog.id }}"
              data-bs-slide="prev"
            >
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button
              class="carousel-control-next"
              type="button"
              data-bs-target="#carousel-{{ blog.id }}"
              data-bs-slide="next"
            >
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          {% else %}
          <div
            style="height: 300px; background-color: #f0f2f5; display: flex; flex-direction: column; justify-content: center; align-items: center; color: #adb5bd; border-radius: 16px 16px 0 0;"
          >
            <i class="fas fa-image fa-3x mb-3"></i>
            <p>No image available</p>
          </div>
          {% endif %}

          <div class="card-content">
            <h2 class="card-title">{{ blog.name }}</h2>
            <div class="divider"></div>
            <div class="blog-meta">
              <div><i class="fas fa-user-circle me-1"></i>{{ blog.author.username }}</div>
              <div><i class="far fa-calendar-alt me-1"></i>{{ blog.created_at|date:"M d, Y" }}</div>
            </div>

            <div class="text-container">
              <div id="post-{{ blog.id }}" class="blog-text">
                <p class="card-text">{{ blog.description }}</p>
              </div>
              {% if blog.description|wordcount > 75 %}
              <div class="text-controls">
                <a href="#post-{{ blog.id }}" class="see-more-link" aria-label="Expand content">Read More</a>
                <a href="#" class="see-less-link" aria-label="Collapse content">Show Less</a>
              </div>
              {% endif %}
            </div>

            <div class="blog-actions-panel">
              {% if user.is_authenticated %}
              <div class="blog-like">
                <a
                  href="{% url 'Blog:like_blog' blog.id %}"
                  class="btn btn-sm {% if user in blog.likes.all %}btn-like-active{% else %}btn-outline-secondary{% endif %}"
                >
                  <i class="{% if user in blog.likes.all %}fas{% else %}far{% endif %} fa-heart heart-icon"></i>
                  <span>{{ blog.likes.count }}</span>
                </a>
              </div>
              {% else %}
              <div class="blog-like">
                <a href="{% url 'Blog:user_login' %}" class="btn btn-sm btn-outline-secondary">
                  <i class="far fa-heart"></i> Login
                </a>
              </div>
              {% endif %}

              {% if request.user == blog.author %}
              <div class="author-actions">
                <a href="{% url 'Blog:edit' blog.id %}" class="btn btn-custom btn-edit"><i class="fas fa-edit"></i> Edit</a>
                <a
                  href="{% url 'Blog:delete' blog.id %}"
                  class="btn btn-custom btn-delete"
                  onclick="return confirm('Are you sure you want to delete this blog post?');"
                >
                  <i class="fas fa-trash"></i> Delete
                </a>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-lg-8 mx-auto">
        <div class="no-content-message">
          <i class="fas fa-compass fa-3x mb-3 floating-icon"></i>
          <h3>No blogs available yet</h3>
          <p>Be the first to share your travel experiences!</p>
          {% if user.is_authenticated %}
          <a href="{% url 'Blog:blog_post' %}" class="btn btn-primary mt-3"><i class="fas fa-pen me-2"></i>Create Your First Blog</a>
          {% else %}
          <a
            href="{% url 'Blog:user_login' %}?next={% url 'Blog:blog_post' %}"
            class="btn btn-primary mt-3"
          ><i class="fas fa-sign-in-alt me-2"></i>Login to Create Blog</a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

EBR/Blog/templates/my_blogs.html
{% extends 'home.html' %}

{% block content %}
  <div class="container py-1">
    <h3 class="mb-5 text-center">Your Posted Blogs</h3>
    <div class="row">
      {% for blog in blogs %}
      <div class="col-lg-8 mx-auto mb-5">
        <div class="blog-card">
          <!-- Carousel for blog images -->
          {% if blog.images.all %}
          <div id="carousel-{{ blog.id }}" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              {% for image in blog.images.all %}
                <button type="button" data-bs-target="#carousel-{{ blog.id }}" 
                        data-bs-slide-to="{{ forloop.counter0 }}" 
                        class="{% if forloop.first %}active{% endif %}" 
                        aria-label="Slide {{ forloop.counter }}"></button>
              {% endfor %}
            </div>
            <div class="carousel-inner">
              {% for image in blog.images.all %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                  <img src="{{ image.image.url }}" class="d-block w-100" alt="{{ blog.name }}">
                </div>
              {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel-{{ blog.id }}" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel-{{ blog.id }}" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          {% else %}
            <div style="height: 300px; background-color: #f0f2f5; display: flex; flex-direction: column; justify-content: center; align-items: center; color: #adb5bd; border-radius: 16px 16px 0 0;">
              <i class="fas fa-image fa-3x mb-3"></i>
              <p>No image available</p>
            </div>
          {% endif %}

          <!-- Blog content -->
          <div class="card-content">
            <h2 class="card-title">{{ blog.name }}</h2>
            <div class="divider"></div>
            <div class="blog-meta">
              <div>
                <i class="fas fa-user-circle me-1"></i> 
                {{ blog.author.username }}
              </div>
              <div>
                <i class="far fa-calendar-alt me-1"></i>
                {{ blog.created_at|date:"M d, Y" }}
              </div>
            </div>
            <div class="text-container">
              <div id="post-{{ blog.id }}" class="blog-text">
                <p class="card-text">{{ blog.description }}</p>
              </div>
              {% if blog.description|wordcount > 75 %}
              <div class="text-controls">
                <a href="#post-{{ blog.id }}" class="see-more-link" aria-label="Expand content">Read More</a>
                <a href="#" class="see-less-link" aria-label="Collapse content">Show Less</a>
              </div>
              {% endif %}
            </div>
            <!-- Blog actions -->
            <div class="blog-actions-panel">
              {% if user.is_authenticated %}
              <div class="blog-like">
                <a href="{% url 'Blog:like_blog' blog.id %}" class="btn btn-sm {% if user in blog.likes.all %}btn-like-active{% else %}btn-outline-secondary{% endif %}">
                  <i class="{% if user in blog.likes.all %}fas{% else %}far{% endif %} fa-heart heart-icon"></i>
                  <span>{{ blog.likes.count }}</span>
                </a>
              </div>
              {% endif %}
              <div class="author-actions">
                <a href="{% url 'Blog:edit' blog.id %}" class="btn btn-custom btn-edit">
                  <i class="fas fa-edit"></i> Edit
                </a>
                <a href="{% url 'Blog:delete' blog.id %}" class="btn btn-custom btn-delete"
                  onclick="return confirm('Are you sure you want to delete this blog post?');">
                  <i class="fas fa-trash"></i> Delete
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-lg-8 mx-auto">
        <div class="no-content-message">
          <i class="fas fa-compass fa-3x mb-3 floating-icon"></i>
          <h3>You haven't posted any blogs yet</h3>
          <p>Start sharing your experiences!</p>
          <a href="{% url 'Blog:blog_post' %}" class="btn btn-primary mt-3">
            <i class="fas fa-pen me-2"></i>Create Your First Blog
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

EBR/Blog/templates/trending.html
{% extends 'home.html' %}

{% block content %}
<div class="container py-1">
  <h3 class="mb-5 text-center">Trending Blogs</h3>
    <div class="row">
      {% for blog in blogs %}
      <div class="col-lg-8 mx-auto mb-5">
        <div class="blog-card">
          <!-- Carousel for blog images -->
          {% if blog.images.all %}
          <div id="carousel-{{ blog.id }}" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              {% for image in blog.images.all %}
                <button type="button" data-bs-target="#carousel-{{ blog.id }}" 
                        data-bs-slide-to="{{ forloop.counter0 }}" 
                        class="{% if forloop.first %}active{% endif %}" 
                        aria-label="Slide {{ forloop.counter }}"></button>
              {% endfor %}
            </div>
            <div class="carousel-inner">
              {% for image in blog.images.all %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                  <img src="{{ image.image.url }}" class="d-block w-100" alt="{{ blog.name }}">
                </div>
              {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel-{{ blog.id }}" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel-{{ blog.id }}" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          {% else %}
            <div style="height: 300px; background-color: #f0f2f5; display: flex; flex-direction: column; justify-content: center; align-items: center; color: #adb5bd; border-radius: 16px 16px 0 0;">
              <i class="fas fa-image fa-3x mb-3"></i>
              <p>No image available</p>
            </div>
          {% endif %}

          <!-- Blog content -->
          <div class="card-content">
            <h2 class="card-title">{{ blog.name }}</h2>
            <div class="divider"></div>
            <div class="blog-meta">
              <div>
                <i class="fas fa-user-circle me-1"></i> 
                {{ blog.author.username }}
              </div>
              <div>
                <i class="far fa-calendar-alt me-1"></i>
                {{ blog.created_at|date:"M d, Y" }}
              </div>
            </div>
            <div class="text-container">
              <div id="post-{{ blog.id }}" class="blog-text">
                <p class="card-text">{{ blog.description }}</p>
              </div>
              {% if blog.description|wordcount > 75 %}
              <div class="text-controls">
                <a href="#post-{{ blog.id }}" class="see-more-link" aria-label="Expand content">Read More</a>
                <a href="#" class="see-less-link" aria-label="Collapse content">Show Less</a>
              </div>
              {% endif %}
            </div>
            <!-- Blog actions -->
            <div class="blog-actions-panel">
              {% if user.is_authenticated %}
              <div class="blog-like">
                <a href="{% url 'Blog:like_blog' blog.id %}" class="btn btn-sm {% if user in blog.likes.all %}btn-like-active{% else %}btn-outline-secondary{% endif %}">
                  <i class="{% if user in blog.likes.all %}fas{% else %}far{% endif %} fa-heart heart-icon"></i>
                  <span>{{ blog.likes.count }}</span>
                </a>
              </div>
              {% endif %}
              {% if request.user == blog.author %}
              <div class="author-actions">
                <a href="{% url 'Blog:edit' blog.id %}" class="btn btn-custom btn-edit">
                  <i class="fas fa-edit"></i> Edit
                </a>
                <a href="{% url 'Blog:delete' blog.id %}" class="btn btn-custom btn-delete"
                  onclick="return confirm('Are you sure you want to delete this blog post?');">
                  <i class="fas fa-trash"></i> Delete
                </a>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-lg-8 mx-auto">
        <div class="no-content-message">
          <i class="fas fa-compass fa-3x mb-3 floating-icon"></i>
          <h3>No trending blogs available</h3>
          <p>Check back later for popular posts!</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

EBR/Blog/templates/user_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'Blog/css/registration.css' %}">
</head>
<body>
    


    <div class="registration-container">
        <div class="registration-card">
            <h2 class="text-center mb-4" style="color: var(--accent-color);">
                <i class="fas fa-sign-in-alt me-2"></i>Welcome Back
            </h2>
            
            <form method="POST">
                {% csrf_token %}

                
                <div class="input-group">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" id="username" name="username" class="form-control" 
                           placeholder="Enter your username" required>
                    <i class="fas fa-user input-icon"></i>
                </div>

                
                <div class="input-group">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" id="password" name="password" class="form-control" 
                           placeholder="Enter your secret phrase" required>
                    <i class="fas fa-lock input-icon"></i>
                </div>

                <button type="submit" class="btn btn-register btn-primary w-100 mt-3">
                    Continue Journey <i class="fas fa-arrow-right ms-2"></i>
                </button>
            </form>

            <div class="text-center mt-4">
                <p class="text-muted">New to us? 
                    <a href="{% url 'Blog:user_registration' %}" class="login-link">Create Account</a>
                </p>
            </div>
        </div>
    </div>
</body>
</html>